// Code generated by hand for the corpus. DO NOT EDIT.

package fixture

//dokimi:mutate-include

// triple returns x times three. The directive after the package clause has
// no effect.
func triple(x int) int {
	return x * 3
}
